### ISSUE TITLE
Help! Strange messages in running dataset/train-tokenizer.py

### ISSUE THREAD

**Issue by mikeda100** [s-JoL/Open-Llama#13] opened 2023-04-15 02:34 UTC
Hi there,

Could you please help - what's problem with these strange messages?

Thanks a lot!

---------------------------------------------------------

Loading data from data/pretrain_data/part-pile-603.jsonl.zst
trainer_interface.cc(367) LOG(INFO) Reserved chars are found. Skipped: Q:

Using sed transliterate command in python

So there is this sed command that allows you to transform the quality code in ASCII into bar symbols: 
sed -e 'n;n;n;y/!"#$%&'\''()*+,-.\/0123456789:;<=>?@ABCDEFGHIJKL/▁▁▁▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇██████/' myfile.fastq

I have been checking ways to do the same in python, but I have not found a solution I can use. Maybe pysed or re.sub, but I do not even know how to write the ASCII code in a string without python getting mixed up the characters.

A:

So, you want to transliterate characters in the 3rd line of your FASTQ file?
You can use str.translate on translation table built with str.maketrans:
#!/usr/bin/env python3
lut = str.maketrans('''!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKL''',
                    '''▁▁▁▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇██████''')

with open('/path/to/fastq') as f:
    line3 = f.readlines()[3].strip()

print(line3.translate(lut))

For a sample file from Wikipedia:
@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65

the Python script above will produce:
▁▁▁▂▁▁▁▁▂▂▂▂▂▂▁▁▁▂▂▂▁▁▁▁▁▂▃▃▂▂▂▂▂▂▁▁▂▂▂▂▄▄▇▇▇▆▆▆▆▆▆▇▇▇▇▇▇▇▄▄

However, note that according to FASTQ format description on Wikipedia, your translation table is incorrect. The character ! represents the lowest quality while ~ is the highest (not L as you have).
Also note that quality value characters directly map the ASCII character range !-~ to the quality value. In other words, we can build the translation table programmatically:
span = ord('█') - ord('▁') + 1
src = ''.join(chr(c) for c in range(ord('!'), ord('~')+1))
dst = ''.join(chr(ord('▁') + span*(ord(c)-ord('!'))//len(src)) for c in src)
lut = str.maketrans(src, dst)
Loading data from data/pretrain_data/part-pile-3372.jsonl.zst
Loading data from data/pretrain_data/part-pile-1704.jsonl.zst

**Comment by s-JoL** [comment] 2023-04-15 04:19
This is a duplicate of the [issue](https://github.com/s-JoL/Open-Llama/issues/12).

**Closed by s-JoL** 2023-04-15 04:19 UTC
